"""movie_list_association

Revision ID: f54d9f430501
Revises: 1f23cd948ee2
Create Date: 2023-10-13 18:45:30.584917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f54d9f430501'
down_revision: Union[str, None] = '1f23cd948ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_list_association',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('movie_list_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['movie_list_id'], ['movie_list.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'movie_list_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_list_association')
    # ### end Alembic commands ###
