"""Movie table

Revision ID: 3476e1be9b76
Revises: 86f96ea85381
Create Date: 2023-09-27 21:34:59.855124

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3476e1be9b76"
down_revision: Union[str, None] = "86f96ea85381"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movie",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("genre_ids", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("original_language", sa.String(), nullable=True),
        sa.Column("original_title", sa.String(), nullable=True),
        sa.Column("overview", sa.String(), nullable=True),
        sa.Column("poster_path", sa.String(), nullable=True),
        sa.Column("backdrop_path", sa.String(), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("release_year", sa.Integer(), nullable=True),
        sa.Column("popularity", sa.Double(), nullable=True),
        sa.Column("vote_average", sa.Double(), nullable=True),
        sa.Column("vote_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movie")
    # ### end Alembic commands ###
