"""constraints

Revision ID: a8d4725123bd
Revises: 78ee9804cef5
Create Date: 2023-10-01 23:29:12.126314

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8d4725123bd"
down_revision: Union[str, None] = "78ee9804cef5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "movie", ["id"])
    op.create_unique_constraint(None, "movie_genre", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "movie_genre", type_="unique")
    op.drop_constraint(None, "movie", type_="unique")
    # ### end Alembic commands ###
